Avivash/filsnap demo
FundRing/fundring pull request #8
Opened 2023-08-24 23:10 UTC by avivash

# Description

- Add `/filfund` route that allows funds to be contributed via Fil snap

## Link to issue

Please add a link to any relevant issues/tickets

## Type of change

- [x] New feature (non-breaking change that adds functionality)

## Screenshots/Screencaps
https://www.loom.com/share/80c56f24347846e59af5eb968b37e899?sid=0f8a0b68-b03e-4c87-9a59-21c7b7767327

## Staging Domain

https://fundring-filsnap.fission.app/

2023-08-31 10:45 UTC, hugomrdias commented
it looks good but AFAICS its not actually using the filsnap API and the tx insights are not even returning anything (which is probably a bug).

2023-09-12 16:10 UTC, hugomrdias requested changes
Please update adapter to v1.0.0 and use "Filecoin Wallet" in user facing messages.

2023-09-12 16:10 UTC, hugomrdias commented on src/routes/filfund/components/FundRingWidget/Connected.svelte
> +  })
The new adapter version has a `rpc()` method that returns a rpc client configured by the filsnap.

2023-09-12 16:10 UTC, hugomrdias commented on src/routes/filfund/components/FundRingWidget/Disconnected.svelte
> +    const hasFlask = await FilsnapAdapter.hasFlask()
```suggestion
    const hasFlask = await FilsnapAdapter.hasSnaps()
```

2023-09-12 16:10 UTC, hugomrdias commented on src/routes/filfund/components/FundRingWidget/Disconnected.svelte
> +      const isSnapConnected = await FilsnapAdapter.isConnected()
```suggestion
      const isSnapConnected = await FilsnapAdapter.isAvailable()
```

2023-09-13 17:59 UTC, avivash commented on src/routes/filfund/components/FundRingWidget/Connected.svelte
> +      '*'
updated 👍🏼

2023-09-13 18:11 UTC, avivash commented
thanks @hugomrdias! I've updated the PR as per your feedback 👍🏼

2023-09-18 15:56 UTC, hugomrdias approved these changes
LGTM

2023-09-18 16:06 UTC, merged